"""add class roster

Revision ID: 08319dda7d97
Revises: 0694cf704e9f
Create Date: 2026-09-17 23:08:02.053700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08319dda7d97'
down_revision: Union[str, Sequence[str], None] = '0694cf704e9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_roster',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('student_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_id', 'name', name='uq_class_roster_class_name')
    )
    with op.batch_alter_table('class_roster', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_class_roster_class_id'), ['class_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_roster', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_class_roster_class_id'))

    op.drop_table('class_roster')
    # ### end Alembic commands ###
