"""add homework ledger

Revision ID: 3526c4423f56
Revises: 08319dda7d97
Create Date: 2026-09-17 23:19:36.575020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3526c4423f56'
down_revision: Union[str, Sequence[str], None] = '08319dda7d97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('homework_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('scoring_mode', sa.String(length=16), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('archived', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('homework_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_homework_items_class_id'), ['class_id'], unique=False)

    op.create_table('homework_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('student_name', sa.String(length=128), nullable=False),
    sa.Column('student_id', sa.String(length=64), nullable=True),
    sa.Column('value', sa.String(length=64), nullable=False),
    sa.Column('score_value', sa.Float(), nullable=True),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['homework_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'student_name', 'record_date', name='uq_homework_record_item_student_date')
    )
    with op.batch_alter_table('homework_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_homework_records_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_homework_records_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_homework_records_record_date'), ['record_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_homework_records_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_homework_records_student_name'), ['student_name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('homework_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_homework_records_student_name'))
        batch_op.drop_index(batch_op.f('ix_homework_records_student_id'))
        batch_op.drop_index(batch_op.f('ix_homework_records_record_date'))
        batch_op.drop_index(batch_op.f('ix_homework_records_item_id'))
        batch_op.drop_index(batch_op.f('ix_homework_records_class_id'))

    op.drop_table('homework_records')
    with op.batch_alter_table('homework_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_homework_items_class_id'))

    op.drop_table('homework_items')
    # ### end Alembic commands ###
