"""add exams

Revision ID: 757095a99fd5
Revises: 3526c4423f56
Create Date: 2026-09-17 23:19:53.253996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '757095a99fd5'
down_revision: Union[str, Sequence[str], None] = '3526c4423f56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('exam_date', sa.Date(), nullable=False),
    sa.Column('subject', sa.String(length=32), nullable=False),
    sa.Column('full_score', sa.Float(), nullable=False),
    sa.Column('exam_type', sa.String(length=32), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exams_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exams_exam_date'), ['exam_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_exams_status'), ['status'], unique=False)

    op.create_table('exam_papers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('student_name', sa.String(length=128), nullable=False),
    sa.Column('student_id', sa.String(length=64), nullable=True),
    sa.Column('image_paths', sa.JSON(), nullable=False),
    sa.Column('ocr_status', sa.String(length=16), nullable=False),
    sa.Column('ocr_error', sa.Text(), nullable=True),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.Column('question_results', sa.JSON(), nullable=False),
    sa.Column('teacher_edited', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id', 'student_name', name='uq_exam_paper_exam_student')
    )
    with op.batch_alter_table('exam_papers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_papers_exam_id'), ['exam_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_papers_ocr_status'), ['ocr_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_papers_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_papers_student_name'), ['student_name'], unique=False)

    op.create_table('exam_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('report_markdown', sa.Text(), nullable=False),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exam_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_reports_exam_id'), ['exam_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_reports_exam_id'))

    op.drop_table('exam_reports')
    with op.batch_alter_table('exam_papers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_papers_student_name'))
        batch_op.drop_index(batch_op.f('ix_exam_papers_student_id'))
        batch_op.drop_index(batch_op.f('ix_exam_papers_ocr_status'))
        batch_op.drop_index(batch_op.f('ix_exam_papers_exam_id'))

    op.drop_table('exam_papers')
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exams_status'))
        batch_op.drop_index(batch_op.f('ix_exams_exam_date'))
        batch_op.drop_index(batch_op.f('ix_exams_class_id'))

    op.drop_table('exams')
    # ### end Alembic commands ###
