"""add class merge

Revision ID: b38655eebf98
Revises: ee89605485ef
Create Date: 2026-09-17 23:47:25.714692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b38655eebf98'
down_revision: Union[str, Sequence[str], None] = 'ee89605485ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_merge_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_class_id', sa.Integer(), nullable=False),
    sa.Column('source_class_name', sa.String(length=128), nullable=False),
    sa.Column('target_class_id', sa.Integer(), nullable=False),
    sa.Column('target_class_name', sa.String(length=128), nullable=False),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('class_merge_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_class_merge_logs_source_class_id'), ['source_class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_merge_logs_target_class_id'), ['target_class_id'], unique=False)

    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('merged_into_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('merged_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_classes_merged_into_id'), ['merged_into_id'], unique=False)
        # 显式命名外键(SQLite 批量模式下未命名约束会在 downgrade 失败,见 alembic naming 文档)
        batch_op.create_foreign_key('fk_classes_merged_into', 'classes', ['merged_into_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_classes_merged_into', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_classes_merged_into_id'))
        batch_op.drop_column('merged_at')
        batch_op.drop_column('merged_into_id')

    with op.batch_alter_table('class_merge_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_class_merge_logs_target_class_id'))
        batch_op.drop_index(batch_op.f('ix_class_merge_logs_source_class_id'))

    op.drop_table('class_merge_logs')
    # ### end Alembic commands ###
