"""add practice sheets

Revision ID: b924fa2a598d
Revises: 49a0a23dc150
Create Date: 2026-09-18 01:37:01.563315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b924fa2a598d'
down_revision: Union[str, Sequence[str], None] = '49a0a23dc150'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('practice_sheets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('source', sa.JSON(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('worksheet_markdown', sa.Text(), nullable=False),
    sa.Column('answer_markdown', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name='fk_practice_sheets_class_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('practice_sheets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_practice_sheets_class_id'), ['class_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practice_sheets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_practice_sheets_class_id'))

    op.drop_table('practice_sheets')
    # ### end Alembic commands ###
