"""baseline schema

Revision ID: eaca32fbbc05
Revises: 
Create Date: 2026-09-17 22:03:11.428711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaca32fbbc05'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('correction_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.String(length=64), nullable=True),
    sa.Column('student_name', sa.String(length=128), nullable=False),
    sa.Column('student_id', sa.String(length=64), nullable=True),
    sa.Column('pipeline_choice', sa.String(length=32), nullable=False),
    sa.Column('pipeline_used', sa.String(length=32), nullable=True),
    sa.Column('grading_standard', sa.String(length=16), nullable=False),
    sa.Column('detail_level', sa.String(length=16), nullable=False),
    sa.Column('require_ocr_review', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('fallback_triggered', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('image_paths', sa.JSON(), nullable=False),
    sa.Column('ocr_result', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('edited_report', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('correction_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_correction_tasks_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_correction_tasks_status'), ['status'], unique=False)

    op.create_table('students',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('student_id', sa.String(length=64), nullable=True),
    sa.Column('class_name', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_student_id'), ['student_id'], unique=False)

    op.create_table('error_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('student_name', sa.String(length=128), nullable=False),
    sa.Column('student_id', sa.String(length=64), nullable=True),
    sa.Column('error_type', sa.String(length=64), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('corrected_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['correction_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('error_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_error_records_error_type'), ['error_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_error_records_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_error_records_student_name'), ['student_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_error_records_task_id'), ['task_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('error_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_error_records_task_id'))
        batch_op.drop_index(batch_op.f('ix_error_records_student_name'))
        batch_op.drop_index(batch_op.f('ix_error_records_student_id'))
        batch_op.drop_index(batch_op.f('ix_error_records_error_type'))

    op.drop_table('error_records')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_student_id'))
        batch_op.drop_index(batch_op.f('ix_students_name'))

    op.drop_table('students')
    with op.batch_alter_table('correction_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_correction_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_correction_tasks_batch_id'))

    op.drop_table('correction_tasks')
    # ### end Alembic commands ###
