"""add style profiles

Revision ID: ee89605485ef
Revises: 757095a99fd5
Create Date: 2026-09-17 23:31:40.211745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee89605485ef'
down_revision: Union[str, Sequence[str], None] = '757095a99fd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('style_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('source_task_id', sa.Integer(), nullable=True),
    sa.Column('source_student_name', sa.String(length=128), nullable=True),
    sa.Column('style_json', sa.JSON(), nullable=False),
    sa.Column('narrative', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('style_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_style_profiles_source_task_id'), ['source_task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_style_profiles_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('style_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_style_profiles_status'))
        batch_op.drop_index(batch_op.f('ix_style_profiles_source_task_id'))

    op.drop_table('style_profiles')
    # ### end Alembic commands ###
